#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Oct 16 16:03:33 CST 2020
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 48f0101913cf4fbb8402706cc8a53dc1 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot wire_and_or_test_behav xil_defaultlib.wire_and_or_test xil_defaultlib.glbl -log elaborate.log"
xelab -wto 48f0101913cf4fbb8402706cc8a53dc1 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot wire_and_or_test_behav xil_defaultlib.wire_and_or_test xil_defaultlib.glbl -log elaborate.log

