#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Oct 15 16:47:53 CST 2020
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 83fe4ce420d540afa32569b7cc3c6f7b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot and_gate_test_behav xil_defaultlib.and_gate_test xil_defaultlib.glbl -log elaborate.log"
xelab -wto 83fe4ce420d540afa32569b7cc3c6f7b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot and_gate_test_behav xil_defaultlib.and_gate_test xil_defaultlib.glbl -log elaborate.log

